# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'Hot')], default=1, verbose_name='状态'),
        ),
    ]
