# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20190827_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='images',
            field=models.CharField(default=1, max_length=256, verbose_name='图片'),
            preserve_default=False,
        ),
    ]
