# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
