# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phonenumber',
        ),
    ]
