# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 13:06
from __future__ import unicode_literals

import apps.PAGES.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.IntegerField(choices=[(1, '姓名'), (2, '价格'), (3, '评级')], null=True, validators=[apps.PAGES.validator.valid_difficulty], verbose_name='商品分类')),
                ('title', models.CharField(max_length=256, null=True, unique=True, verbose_name='商品名字')),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PAGES.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '鞋库',
                'verbose_name_plural': '鞋库',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='tag',
            field=models.ManyToManyField(to='PAGES.Tag', verbose_name='题目标签'),
        ),
    ]
