# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 13:39
from __future__ import unicode_literals

import apps.PAGES.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shoes',
            field=models.IntegerField(choices=[(1, '男性'), (2, '价格'), (3, '女性'), (3, '儿童'), (3, '体育'), (3, '品牌'), (3, '颜色'), (3, '大小')], null=True, validators=[apps.PAGES.validator.valid_difficulty], verbose_name='商品分类'),
        ),
    ]
