# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0002_auto_20190814_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='content',
            field=models.TextField(null=True, verbose_name='商品详情'),
        ),
    ]
