# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 08:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0003_shop_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='商品详情'),
        ),
    ]
