# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 02:46
from __future__ import unicode_literals

import apps.PAGES.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0004_auto_20190820_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shoes',
            field=models.IntegerField(choices=[(1, '男性'), (2, '价格'), (3, '女性'), (4, '颜色'), (5, '大小')], null=True, validators=[apps.PAGES.validator.valid_difficulty], verbose_name='商品分类'),
        ),
    ]
