# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0005_auto_20190821_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tag',
            field=models.ManyToManyField(to='PAGES.Tag', verbose_name='商品标签'),
        ),
    ]
