# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0006_auto_20190821_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='商品价格'),
        ),
    ]
