# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0007_shop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='tag',
        ),
        migrations.AddField(
            model_name='shop',
            name='tag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PAGES.Tag', verbose_name='商品标签'),
            preserve_default=False,
        ),
    ]
