# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0008_auto_20190824_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAGES.Tag', verbose_name='商品标签'),
        ),
    ]
