# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0009_auto_20190824_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='tag',
        ),
        migrations.AddField(
            model_name='shop',
            name='tag',
            field=models.ManyToManyField(to='PAGES.Tag', verbose_name='商品标签'),
        ),
    ]
