# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-24 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAGES', '0010_auto_20190824_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=1, upload_to='shoes', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
